from typing import Protocol
from uuid import UUID

from notifservice.data.entities.user import User


class UserRepo(Protocol):
    async def create(self, user: User) -> User | None: ...
    async def update(self, user: User) -> User | None: ...
    async def delete(self, id: UUID) -> User | None: ...
    async def getByID(self, id: UUID) -> User | None: ...
